[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = 0

[profile.release]
codegen-units = 1
lto = true

[dependencies]
anyhow = "1.0.93"
itertools = "0.13.0"
nom = "7.1.3"
rayon = "1.10.0"
regex = "1.11.1"
