[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# itertools = "0.10.1"
# regex = "1.5.4"
strum = { version = "0.26.3", features = ["derive"] }

[features]
