[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[dependencies]
anyhow = "1.0.68"
itertools = "0.10.5"
